version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mock-server

  mock-server:
    build:
      context: .
      dockerfile: Dockerfile.mock
    ports:
      - "8081:8081"
