openapi: 3.0.0
info:
  title: Payment API
  version: 1.0.0
  description: API para gerenciar pagamentos

paths:
  /payments:
    post:
      summary: Criar um novo pagamento
      operationId: createPayment
      x-backend-url: "http://192.168.68.130:8081"
      requestBody:
        description: Dados para criar um novo pagamento
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                account_id:
                  type: string
                  description: ID da conta
                  example: "123456"
                amount:
                  type: number
                  format: float
                  description: Valor do pagamento
                  example: 100.50
      responses:
        "201":
          description: Pagamento criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment_id:
                    type: string
                    format: uuid
                    description: ID do pagamento
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  amount:
                    type: number
                    format: float
                    description: Valor do pagamento
                    example: 100.50
                  created_at:
                    type: string
                    format: date-time
                    description: Data de criação do pagamento
                    example: "2024-05-27T14:53:00Z"
                  created_by:
                    type: string
                    description: ID da conta que criou o pagamento
                    example: "123456"
                  status:
                    type: string
                    enum: [Authorized, Unauthorized]
                    description: Status do pagamento
                    example: "Authorized"

  /payments/{payment_id}:
    get:
      summary: Obter detalhes de um pagamento
      operationId: getPayment
      x-backend-url: "http://192.168.68.130:8081"
      parameters:
        - name: payment_id
          in: path
          required: true
          description: ID do pagamento
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        "200":
          description: Detalhes do pagamento
          content:
            application/json:
              schema:
                type: object
                properties:
                  payment_id:
                    type: string
                    format: uuid
                    description: ID do pagamento
                    example: "550e8400-e29b-41d4-a716-446655440000"
                  amount:
                    type: number
                    format: float
                    description: Valor do pagamento
                    example: 100.50
                  created_at:
                    type: string
                    format: date-time
                    description: Data de criação do pagamento
                    example: "2024-05-27T14:53:00Z"
                  created_by:
                    type: string
                    description: ID da conta que criou o pagamento
                    example: "123456"
                  status:
                    type: string
                    enum: [Authorized, Unauthorized]
                    description: Status do pagamento
                    example: "Authorized"
        "404":
          description: Pagamento não encontrado
