name: Review Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Call API for Code Reviewer to Code Evaluation
      run: |
        curl -X GET "http://code-reviewer-genai-alb-62547224.us-east-1.elb.amazonaws.com/review?action=evaluate_code&pr_number=${{ github.event.pull_request.number }}"

    - name: Call API for Code Reviewer to Business rule Evaluation
      run: |
        curl -X GET "http://code-reviewer-genai-alb-62547224.us-east-1.elb.amazonaws.com/review?action=evaluate_business_rules&pr_number=${{ github.event.pull_request.number }}"

    - name: Call API for Code Reviewer to design patterns Evaluation
      run: |
        curl -X GET "http://code-reviewer-genai-alb-62547224.us-east-1.elb.amazonaws.com/review?action=evaluate_company_standards&pr_number=${{ github.event.pull_request.number }}"
